// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/item_ingredient.proto

package item_ingredient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddItemIngredientRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UuidItem       string                 `protobuf:"bytes,1,opt,name=uuid_item,json=uuidItem,proto3" json:"uuid_item,omitempty"`
	UuidIngredient string                 `protobuf:"bytes,2,opt,name=uuid_ingredient,json=uuidIngredient,proto3" json:"uuid_ingredient,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddItemIngredientRequest) Reset() {
	*x = AddItemIngredientRequest{}
	mi := &file_proto_item_ingredient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemIngredientRequest) ProtoMessage() {}

func (x *AddItemIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_ingredient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemIngredientRequest.ProtoReflect.Descriptor instead.
func (*AddItemIngredientRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_ingredient_proto_rawDescGZIP(), []int{0}
}

func (x *AddItemIngredientRequest) GetUuidItem() string {
	if x != nil {
		return x.UuidItem
	}
	return ""
}

func (x *AddItemIngredientRequest) GetUuidIngredient() string {
	if x != nil {
		return x.UuidIngredient
	}
	return ""
}

type AddItemIngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemIngredientResponse) Reset() {
	*x = AddItemIngredientResponse{}
	mi := &file_proto_item_ingredient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemIngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemIngredientResponse) ProtoMessage() {}

func (x *AddItemIngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_ingredient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemIngredientResponse.ProtoReflect.Descriptor instead.
func (*AddItemIngredientResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_ingredient_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemIngredientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddItemIngredientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteItemIngredientRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UuidItem       string                 `protobuf:"bytes,1,opt,name=uuid_item,json=uuidItem,proto3" json:"uuid_item,omitempty"`
	UuidIngredient string                 `protobuf:"bytes,2,opt,name=uuid_ingredient,json=uuidIngredient,proto3" json:"uuid_ingredient,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteItemIngredientRequest) Reset() {
	*x = DeleteItemIngredientRequest{}
	mi := &file_proto_item_ingredient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemIngredientRequest) ProtoMessage() {}

func (x *DeleteItemIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_ingredient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemIngredientRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemIngredientRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_ingredient_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteItemIngredientRequest) GetUuidItem() string {
	if x != nil {
		return x.UuidItem
	}
	return ""
}

func (x *DeleteItemIngredientRequest) GetUuidIngredient() string {
	if x != nil {
		return x.UuidIngredient
	}
	return ""
}

type DeleteItemIngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemIngredientResponse) Reset() {
	*x = DeleteItemIngredientResponse{}
	mi := &file_proto_item_ingredient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemIngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemIngredientResponse) ProtoMessage() {}

func (x *DeleteItemIngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_ingredient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemIngredientResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemIngredientResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_ingredient_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteItemIngredientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteItemIngredientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetItemIngredientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidItem      string                 `protobuf:"bytes,1,opt,name=uuid_item,json=uuidItem,proto3" json:"uuid_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemIngredientsRequest) Reset() {
	*x = GetItemIngredientsRequest{}
	mi := &file_proto_item_ingredient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemIngredientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemIngredientsRequest) ProtoMessage() {}

func (x *GetItemIngredientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_ingredient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemIngredientsRequest.ProtoReflect.Descriptor instead.
func (*GetItemIngredientsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_ingredient_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemIngredientsRequest) GetUuidItem() string {
	if x != nil {
		return x.UuidItem
	}
	return ""
}

type ItemIngredient struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UuidItem       string                 `protobuf:"bytes,1,opt,name=uuid_item,json=uuidItem,proto3" json:"uuid_item,omitempty"`
	UuidIngredient string                 `protobuf:"bytes,2,opt,name=uuid_ingredient,json=uuidIngredient,proto3" json:"uuid_ingredient,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ItemIngredient) Reset() {
	*x = ItemIngredient{}
	mi := &file_proto_item_ingredient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemIngredient) ProtoMessage() {}

func (x *ItemIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_ingredient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemIngredient.ProtoReflect.Descriptor instead.
func (*ItemIngredient) Descriptor() ([]byte, []int) {
	return file_proto_item_ingredient_proto_rawDescGZIP(), []int{5}
}

func (x *ItemIngredient) GetUuidItem() string {
	if x != nil {
		return x.UuidItem
	}
	return ""
}

func (x *ItemIngredient) GetUuidIngredient() string {
	if x != nil {
		return x.UuidIngredient
	}
	return ""
}

type GetItemIngredientsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ItemIngredients []*ItemIngredient      `protobuf:"bytes,3,rep,name=item_ingredients,json=itemIngredients,proto3" json:"item_ingredients,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetItemIngredientsResponse) Reset() {
	*x = GetItemIngredientsResponse{}
	mi := &file_proto_item_ingredient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemIngredientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemIngredientsResponse) ProtoMessage() {}

func (x *GetItemIngredientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_ingredient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemIngredientsResponse.ProtoReflect.Descriptor instead.
func (*GetItemIngredientsResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_ingredient_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemIngredientsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetItemIngredientsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetItemIngredientsResponse) GetItemIngredients() []*ItemIngredient {
	if x != nil {
		return x.ItemIngredients
	}
	return nil
}

var File_proto_item_ingredient_proto protoreflect.FileDescriptor

const file_proto_item_ingredient_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/item_ingredient.proto\x12\x0fitem_ingredient\"`\n" +
	"\x18AddItemIngredientRequest\x12\x1b\n" +
	"\tuuid_item\x18\x01 \x01(\tR\buuidItem\x12'\n" +
	"\x0fuuid_ingredient\x18\x02 \x01(\tR\x0euuidIngredient\"O\n" +
	"\x19AddItemIngredientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x1bDeleteItemIngredientRequest\x12\x1b\n" +
	"\tuuid_item\x18\x01 \x01(\tR\buuidItem\x12'\n" +
	"\x0fuuid_ingredient\x18\x02 \x01(\tR\x0euuidIngredient\"R\n" +
	"\x1cDeleteItemIngredientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x19GetItemIngredientsRequest\x12\x1b\n" +
	"\tuuid_item\x18\x01 \x01(\tR\buuidItem\"V\n" +
	"\x0eItemIngredient\x12\x1b\n" +
	"\tuuid_item\x18\x01 \x01(\tR\buuidItem\x12'\n" +
	"\x0fuuid_ingredient\x18\x02 \x01(\tR\x0euuidIngredient\"\x9c\x01\n" +
	"\x1aGetItemIngredientsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12J\n" +
	"\x10item_ingredients\x18\x03 \x03(\v2\x1f.item_ingredient.ItemIngredientR\x0fitemIngredients2\xe7\x02\n" +
	"\x15ItemIngredientService\x12j\n" +
	"\x11AddItemIngredient\x12).item_ingredient.AddItemIngredientRequest\x1a*.item_ingredient.AddItemIngredientResponse\x12s\n" +
	"\x14DeleteItemIngredient\x12,.item_ingredient.DeleteItemIngredientRequest\x1a-.item_ingredient.DeleteItemIngredientResponse\x12m\n" +
	"\x12GetItemIngredients\x12*.item_ingredient.GetItemIngredientsRequest\x1a+.item_ingredient.GetItemIngredientsResponseB9Z7github.com/shirloin/react-go-prac/proto/item_ingredientb\x06proto3"

var (
	file_proto_item_ingredient_proto_rawDescOnce sync.Once
	file_proto_item_ingredient_proto_rawDescData []byte
)

func file_proto_item_ingredient_proto_rawDescGZIP() []byte {
	file_proto_item_ingredient_proto_rawDescOnce.Do(func() {
		file_proto_item_ingredient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_item_ingredient_proto_rawDesc), len(file_proto_item_ingredient_proto_rawDesc)))
	})
	return file_proto_item_ingredient_proto_rawDescData
}

var file_proto_item_ingredient_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_item_ingredient_proto_goTypes = []any{
	(*AddItemIngredientRequest)(nil),     // 0: item_ingredient.AddItemIngredientRequest
	(*AddItemIngredientResponse)(nil),    // 1: item_ingredient.AddItemIngredientResponse
	(*DeleteItemIngredientRequest)(nil),  // 2: item_ingredient.DeleteItemIngredientRequest
	(*DeleteItemIngredientResponse)(nil), // 3: item_ingredient.DeleteItemIngredientResponse
	(*GetItemIngredientsRequest)(nil),    // 4: item_ingredient.GetItemIngredientsRequest
	(*ItemIngredient)(nil),               // 5: item_ingredient.ItemIngredient
	(*GetItemIngredientsResponse)(nil),   // 6: item_ingredient.GetItemIngredientsResponse
}
var file_proto_item_ingredient_proto_depIdxs = []int32{
	5, // 0: item_ingredient.GetItemIngredientsResponse.item_ingredients:type_name -> item_ingredient.ItemIngredient
	0, // 1: item_ingredient.ItemIngredientService.AddItemIngredient:input_type -> item_ingredient.AddItemIngredientRequest
	2, // 2: item_ingredient.ItemIngredientService.DeleteItemIngredient:input_type -> item_ingredient.DeleteItemIngredientRequest
	4, // 3: item_ingredient.ItemIngredientService.GetItemIngredients:input_type -> item_ingredient.GetItemIngredientsRequest
	1, // 4: item_ingredient.ItemIngredientService.AddItemIngredient:output_type -> item_ingredient.AddItemIngredientResponse
	3, // 5: item_ingredient.ItemIngredientService.DeleteItemIngredient:output_type -> item_ingredient.DeleteItemIngredientResponse
	6, // 6: item_ingredient.ItemIngredientService.GetItemIngredients:output_type -> item_ingredient.GetItemIngredientsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_item_ingredient_proto_init() }
func file_proto_item_ingredient_proto_init() {
	if File_proto_item_ingredient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_item_ingredient_proto_rawDesc), len(file_proto_item_ingredient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_item_ingredient_proto_goTypes,
		DependencyIndexes: file_proto_item_ingredient_proto_depIdxs,
		MessageInfos:      file_proto_item_ingredient_proto_msgTypes,
	}.Build()
	File_proto_item_ingredient_proto = out.File
	file_proto_item_ingredient_proto_goTypes = nil
	file_proto_item_ingredient_proto_depIdxs = nil
}
