// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "item_ingredient.proto" (package "item_ingredient", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message item_ingredient.AddItemIngredientRequest
 */
export interface AddItemIngredientRequest {
    /**
     * @generated from protobuf field: string uuid_item = 1
     */
    uuidItem: string;
    /**
     * @generated from protobuf field: string uuid_ingredient = 2
     */
    uuidIngredient: string;
}
/**
 * @generated from protobuf message item_ingredient.AddItemIngredientResponse
 */
export interface AddItemIngredientResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message item_ingredient.DeleteItemIngredientRequest
 */
export interface DeleteItemIngredientRequest {
    /**
     * @generated from protobuf field: string uuid_item = 1
     */
    uuidItem: string;
    /**
     * @generated from protobuf field: string uuid_ingredient = 2
     */
    uuidIngredient: string;
}
/**
 * @generated from protobuf message item_ingredient.DeleteItemIngredientResponse
 */
export interface DeleteItemIngredientResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message item_ingredient.GetItemIngredientsRequest
 */
export interface GetItemIngredientsRequest {
    /**
     * @generated from protobuf field: string uuid_item = 1
     */
    uuidItem: string;
}
/**
 * @generated from protobuf message item_ingredient.ItemIngredient
 */
export interface ItemIngredient {
    /**
     * @generated from protobuf field: string uuid_item = 1
     */
    uuidItem: string;
    /**
     * @generated from protobuf field: string uuid_ingredient = 2
     */
    uuidIngredient: string;
}
/**
 * @generated from protobuf message item_ingredient.GetItemIngredientsResponse
 */
export interface GetItemIngredientsResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: repeated item_ingredient.ItemIngredient item_ingredients = 3
     */
    itemIngredients: ItemIngredient[];
}
// @generated message type with reflection information, may provide speed optimized methods
class AddItemIngredientRequest$Type extends MessageType<AddItemIngredientRequest> {
    constructor() {
        super("item_ingredient.AddItemIngredientRequest", [
            { no: 1, name: "uuid_item", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uuid_ingredient", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddItemIngredientRequest>): AddItemIngredientRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuidItem = "";
        message.uuidIngredient = "";
        if (value !== undefined)
            reflectionMergePartial<AddItemIngredientRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddItemIngredientRequest): AddItemIngredientRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid_item */ 1:
                    message.uuidItem = reader.string();
                    break;
                case /* string uuid_ingredient */ 2:
                    message.uuidIngredient = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddItemIngredientRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid_item = 1; */
        if (message.uuidItem !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuidItem);
        /* string uuid_ingredient = 2; */
        if (message.uuidIngredient !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uuidIngredient);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message item_ingredient.AddItemIngredientRequest
 */
export const AddItemIngredientRequest = new AddItemIngredientRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddItemIngredientResponse$Type extends MessageType<AddItemIngredientResponse> {
    constructor() {
        super("item_ingredient.AddItemIngredientResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddItemIngredientResponse>): AddItemIngredientResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<AddItemIngredientResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddItemIngredientResponse): AddItemIngredientResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddItemIngredientResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message item_ingredient.AddItemIngredientResponse
 */
export const AddItemIngredientResponse = new AddItemIngredientResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteItemIngredientRequest$Type extends MessageType<DeleteItemIngredientRequest> {
    constructor() {
        super("item_ingredient.DeleteItemIngredientRequest", [
            { no: 1, name: "uuid_item", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uuid_ingredient", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteItemIngredientRequest>): DeleteItemIngredientRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuidItem = "";
        message.uuidIngredient = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteItemIngredientRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteItemIngredientRequest): DeleteItemIngredientRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid_item */ 1:
                    message.uuidItem = reader.string();
                    break;
                case /* string uuid_ingredient */ 2:
                    message.uuidIngredient = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteItemIngredientRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid_item = 1; */
        if (message.uuidItem !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuidItem);
        /* string uuid_ingredient = 2; */
        if (message.uuidIngredient !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uuidIngredient);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message item_ingredient.DeleteItemIngredientRequest
 */
export const DeleteItemIngredientRequest = new DeleteItemIngredientRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteItemIngredientResponse$Type extends MessageType<DeleteItemIngredientResponse> {
    constructor() {
        super("item_ingredient.DeleteItemIngredientResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteItemIngredientResponse>): DeleteItemIngredientResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteItemIngredientResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteItemIngredientResponse): DeleteItemIngredientResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteItemIngredientResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message item_ingredient.DeleteItemIngredientResponse
 */
export const DeleteItemIngredientResponse = new DeleteItemIngredientResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetItemIngredientsRequest$Type extends MessageType<GetItemIngredientsRequest> {
    constructor() {
        super("item_ingredient.GetItemIngredientsRequest", [
            { no: 1, name: "uuid_item", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetItemIngredientsRequest>): GetItemIngredientsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuidItem = "";
        if (value !== undefined)
            reflectionMergePartial<GetItemIngredientsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetItemIngredientsRequest): GetItemIngredientsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid_item */ 1:
                    message.uuidItem = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetItemIngredientsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid_item = 1; */
        if (message.uuidItem !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuidItem);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message item_ingredient.GetItemIngredientsRequest
 */
export const GetItemIngredientsRequest = new GetItemIngredientsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ItemIngredient$Type extends MessageType<ItemIngredient> {
    constructor() {
        super("item_ingredient.ItemIngredient", [
            { no: 1, name: "uuid_item", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uuid_ingredient", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ItemIngredient>): ItemIngredient {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uuidItem = "";
        message.uuidIngredient = "";
        if (value !== undefined)
            reflectionMergePartial<ItemIngredient>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ItemIngredient): ItemIngredient {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid_item */ 1:
                    message.uuidItem = reader.string();
                    break;
                case /* string uuid_ingredient */ 2:
                    message.uuidIngredient = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ItemIngredient, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid_item = 1; */
        if (message.uuidItem !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuidItem);
        /* string uuid_ingredient = 2; */
        if (message.uuidIngredient !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uuidIngredient);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message item_ingredient.ItemIngredient
 */
export const ItemIngredient = new ItemIngredient$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetItemIngredientsResponse$Type extends MessageType<GetItemIngredientsResponse> {
    constructor() {
        super("item_ingredient.GetItemIngredientsResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "item_ingredients", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ItemIngredient }
        ]);
    }
    create(value?: PartialMessage<GetItemIngredientsResponse>): GetItemIngredientsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.itemIngredients = [];
        if (value !== undefined)
            reflectionMergePartial<GetItemIngredientsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetItemIngredientsResponse): GetItemIngredientsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* repeated item_ingredient.ItemIngredient item_ingredients */ 3:
                    message.itemIngredients.push(ItemIngredient.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetItemIngredientsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* repeated item_ingredient.ItemIngredient item_ingredients = 3; */
        for (let i = 0; i < message.itemIngredients.length; i++)
            ItemIngredient.internalBinaryWrite(message.itemIngredients[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message item_ingredient.GetItemIngredientsResponse
 */
export const GetItemIngredientsResponse = new GetItemIngredientsResponse$Type();
/**
 * @generated ServiceType for protobuf service item_ingredient.ItemIngredientService
 */
export const ItemIngredientService = new ServiceType("item_ingredient.ItemIngredientService", [
    { name: "AddItemIngredient", options: {}, I: AddItemIngredientRequest, O: AddItemIngredientResponse },
    { name: "DeleteItemIngredient", options: {}, I: DeleteItemIngredientRequest, O: DeleteItemIngredientResponse },
    { name: "GetItemIngredients", options: {}, I: GetItemIngredientsRequest, O: GetItemIngredientsResponse }
]);
