// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "item_ingredient.proto" (package "item_ingredient", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ItemIngredientService } from "./item_ingredient";
import type { GetItemIngredientsResponse } from "./item_ingredient";
import type { GetItemIngredientsRequest } from "./item_ingredient";
import type { DeleteItemIngredientResponse } from "./item_ingredient";
import type { DeleteItemIngredientRequest } from "./item_ingredient";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AddItemIngredientResponse } from "./item_ingredient";
import type { AddItemIngredientRequest } from "./item_ingredient";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * ItemIngredientService handles item-ingredient relationships
 *
 * @generated from protobuf service item_ingredient.ItemIngredientService
 */
export interface IItemIngredientServiceClient {
    /**
     * Add an ingredient to an item
     *
     * @generated from protobuf rpc: AddItemIngredient
     */
    addItemIngredient(input: AddItemIngredientRequest, options?: RpcOptions): UnaryCall<AddItemIngredientRequest, AddItemIngredientResponse>;
    /**
     * Remove an ingredient from an item
     *
     * @generated from protobuf rpc: DeleteItemIngredient
     */
    deleteItemIngredient(input: DeleteItemIngredientRequest, options?: RpcOptions): UnaryCall<DeleteItemIngredientRequest, DeleteItemIngredientResponse>;
    /**
     * Get all ingredients for an item
     *
     * @generated from protobuf rpc: GetItemIngredients
     */
    getItemIngredients(input: GetItemIngredientsRequest, options?: RpcOptions): UnaryCall<GetItemIngredientsRequest, GetItemIngredientsResponse>;
}
/**
 * ItemIngredientService handles item-ingredient relationships
 *
 * @generated from protobuf service item_ingredient.ItemIngredientService
 */
export class ItemIngredientServiceClient implements IItemIngredientServiceClient, ServiceInfo {
    typeName = ItemIngredientService.typeName;
    methods = ItemIngredientService.methods;
    options = ItemIngredientService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Add an ingredient to an item
     *
     * @generated from protobuf rpc: AddItemIngredient
     */
    addItemIngredient(input: AddItemIngredientRequest, options?: RpcOptions): UnaryCall<AddItemIngredientRequest, AddItemIngredientResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddItemIngredientRequest, AddItemIngredientResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Remove an ingredient from an item
     *
     * @generated from protobuf rpc: DeleteItemIngredient
     */
    deleteItemIngredient(input: DeleteItemIngredientRequest, options?: RpcOptions): UnaryCall<DeleteItemIngredientRequest, DeleteItemIngredientResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteItemIngredientRequest, DeleteItemIngredientResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get all ingredients for an item
     *
     * @generated from protobuf rpc: GetItemIngredients
     */
    getItemIngredients(input: GetItemIngredientsRequest, options?: RpcOptions): UnaryCall<GetItemIngredientsRequest, GetItemIngredientsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetItemIngredientsRequest, GetItemIngredientsResponse>("unary", this._transport, method, opt, input);
    }
}
