// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: item_ingredient/item_ingredient.proto

package item_ingredient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemIngredientService_AddItemIngredient_FullMethodName    = "/item_ingredient.ItemIngredientService/AddItemIngredient"
	ItemIngredientService_DeleteItemIngredient_FullMethodName = "/item_ingredient.ItemIngredientService/DeleteItemIngredient"
	ItemIngredientService_GetItemIngredients_FullMethodName   = "/item_ingredient.ItemIngredientService/GetItemIngredients"
)

// ItemIngredientServiceClient is the client API for ItemIngredientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemIngredientService handles item-ingredient relationships
type ItemIngredientServiceClient interface {
	// Add an ingredient to an item
	AddItemIngredient(ctx context.Context, in *AddItemIngredientRequest, opts ...grpc.CallOption) (*AddItemIngredientResponse, error)
	// Remove an ingredient from an item
	DeleteItemIngredient(ctx context.Context, in *DeleteItemIngredientRequest, opts ...grpc.CallOption) (*DeleteItemIngredientResponse, error)
	// Get all ingredients for an item
	GetItemIngredients(ctx context.Context, in *GetItemIngredientsRequest, opts ...grpc.CallOption) (*GetItemIngredientsResponse, error)
}

type itemIngredientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemIngredientServiceClient(cc grpc.ClientConnInterface) ItemIngredientServiceClient {
	return &itemIngredientServiceClient{cc}
}

func (c *itemIngredientServiceClient) AddItemIngredient(ctx context.Context, in *AddItemIngredientRequest, opts ...grpc.CallOption) (*AddItemIngredientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddItemIngredientResponse)
	err := c.cc.Invoke(ctx, ItemIngredientService_AddItemIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemIngredientServiceClient) DeleteItemIngredient(ctx context.Context, in *DeleteItemIngredientRequest, opts ...grpc.CallOption) (*DeleteItemIngredientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteItemIngredientResponse)
	err := c.cc.Invoke(ctx, ItemIngredientService_DeleteItemIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemIngredientServiceClient) GetItemIngredients(ctx context.Context, in *GetItemIngredientsRequest, opts ...grpc.CallOption) (*GetItemIngredientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemIngredientsResponse)
	err := c.cc.Invoke(ctx, ItemIngredientService_GetItemIngredients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemIngredientServiceServer is the server API for ItemIngredientService service.
// All implementations must embed UnimplementedItemIngredientServiceServer
// for forward compatibility.
//
// ItemIngredientService handles item-ingredient relationships
type ItemIngredientServiceServer interface {
	// Add an ingredient to an item
	AddItemIngredient(context.Context, *AddItemIngredientRequest) (*AddItemIngredientResponse, error)
	// Remove an ingredient from an item
	DeleteItemIngredient(context.Context, *DeleteItemIngredientRequest) (*DeleteItemIngredientResponse, error)
	// Get all ingredients for an item
	GetItemIngredients(context.Context, *GetItemIngredientsRequest) (*GetItemIngredientsResponse, error)
	mustEmbedUnimplementedItemIngredientServiceServer()
}

// UnimplementedItemIngredientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemIngredientServiceServer struct{}

func (UnimplementedItemIngredientServiceServer) AddItemIngredient(context.Context, *AddItemIngredientRequest) (*AddItemIngredientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddItemIngredient not implemented")
}
func (UnimplementedItemIngredientServiceServer) DeleteItemIngredient(context.Context, *DeleteItemIngredientRequest) (*DeleteItemIngredientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteItemIngredient not implemented")
}
func (UnimplementedItemIngredientServiceServer) GetItemIngredients(context.Context, *GetItemIngredientsRequest) (*GetItemIngredientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItemIngredients not implemented")
}
func (UnimplementedItemIngredientServiceServer) mustEmbedUnimplementedItemIngredientServiceServer() {}
func (UnimplementedItemIngredientServiceServer) testEmbeddedByValue()                               {}

// UnsafeItemIngredientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemIngredientServiceServer will
// result in compilation errors.
type UnsafeItemIngredientServiceServer interface {
	mustEmbedUnimplementedItemIngredientServiceServer()
}

func RegisterItemIngredientServiceServer(s grpc.ServiceRegistrar, srv ItemIngredientServiceServer) {
	// If the following call panics, it indicates UnimplementedItemIngredientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemIngredientService_ServiceDesc, srv)
}

func _ItemIngredientService_AddItemIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemIngredientServiceServer).AddItemIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemIngredientService_AddItemIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemIngredientServiceServer).AddItemIngredient(ctx, req.(*AddItemIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemIngredientService_DeleteItemIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemIngredientServiceServer).DeleteItemIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemIngredientService_DeleteItemIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemIngredientServiceServer).DeleteItemIngredient(ctx, req.(*DeleteItemIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemIngredientService_GetItemIngredients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemIngredientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemIngredientServiceServer).GetItemIngredients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemIngredientService_GetItemIngredients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemIngredientServiceServer).GetItemIngredients(ctx, req.(*GetItemIngredientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemIngredientService_ServiceDesc is the grpc.ServiceDesc for ItemIngredientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemIngredientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "item_ingredient.ItemIngredientService",
	HandlerType: (*ItemIngredientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItemIngredient",
			Handler:    _ItemIngredientService_AddItemIngredient_Handler,
		},
		{
			MethodName: "DeleteItemIngredient",
			Handler:    _ItemIngredientService_DeleteItemIngredient_Handler,
		},
		{
			MethodName: "GetItemIngredients",
			Handler:    _ItemIngredientService_GetItemIngredients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_ingredient/item_ingredient.proto",
}
